[2025-03-22 14:44:03,415] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:13,651] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\model\\__init__.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:13,800] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:20,760] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\model\\__init__.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:20,914] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:23,927] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\model\\__init__.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:24,066] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:32,340] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\model\\__init__.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:44:32,501] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:20,946] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:20] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:21,467] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:21] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:21,470] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:21] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:21,473] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:21] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:21,650] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:21] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:21,667] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:21] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:30,376] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:30,542] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:32,673] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:32] "[35m[1mGET /openapi/swagger HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:32,753] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:32] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:32,830] ERROR _log() L97   Error on request:
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
    ~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 972, in app
    raise err from None
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
    ~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 972, in app
    raise err from None
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 961, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ~~~~~~~~~~~~~^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 353, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 147, in <module>
    @app.get('/rescue-point', tags=[rescue_point_tag],
                                    ^^
NameError: name 'rs' is not defined - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:32,832] ERROR _log() L97   Error on request:
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
    ~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 972, in app
    raise err from None
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
    ~~~~~~~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 972, in app
    raise err from None
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 961, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ~~~~~~~~~~~~~^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 353, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 147, in <module>
    @app.get('/rescue-point', tags=[rescue_point_tag],
                                    ^^
NameError: name 'rs' is not defined - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:41,972] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:41] "[35m[1mGET /openapi/swagger HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:46:42,072] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:46:42] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:47:12,572] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:47:12,573] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:47:12,577] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:47:14,497] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:47:14] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:47:14,695] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:47:14] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:47:14,711] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:47:14] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:47:14,712] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 14:47:14] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 14:48:12,325] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
